window['musicData'] = [
  {
    id: 1,
    title: 'Golden Hour',
    artist: '慎啸',
    original: 'Golden Hour-JVKE',
    tags: ['vanilla'],
    playCount: 747053,
    duration: 211,
    cover: 'GoldenHour-慎啸.jpg',
    url: '【纯净哈基米】Golden Hour - 慎啸.mp3',
    bvid: 'BV1aQnGzZE8e',
    lyric: 'GoldenHour-慎啸.lrc',
    public_time: 1758890132,
  },
  {
    id: 2,
    title: '基米地',
    artist: 'kizznoluv',
    original: '凄美地-郭顶',
    tags: ['vanilla'],
    playCount: 90926,
    duration: 91,
    cover: '基米地-kizznoluv.jpg',
    url: '【纯净哈基米】基米地（凄美地） - kizznoluv.mp3',
    bvid: 'BV1d5phzXEFs',
    public_time: 1758160800,
  },
  {
    id: 3,
    title: '匆匆哈年',
    artist: '慎啸',
    original: '匆匆那年-王菲',
    tags: ['vanilla'],
    playCount: 169643,
    duration: 242,
    cover: '匆匆哈年-慎啸.jpg',
    url: '【纯净哈基米】匆匆哈年（完整版） - 慎啸.mp3',
    bvid: 'BV1pc42zpEX7',
    public_time: 1760362656,
  },
  {
    id: 4,
    title: '基米说',
    artist: '劉俊朗',
    original: '伯虎说-唐伯虎Annie/伯爵Johnny',
    tags: ['cover', 'DingDongJi'],
    playCount: 7948136,
    duration: 242,
    cover: '基米说-劉俊朗.jpg',
    url: '基米说（完整版） - 劉俊朗.mp3',
    bvid: 'BV1Dua2zyE4G',
    public_time: 1756960147,
  },
  {
    id: 5,
    title: '夜哈',
    artist: '劉俊朗',
    original: '夜曲-周杰伦',
    tags: ['cover', 'vanilla'],
    playCount: 1685507,
    duration: 113,
    cover: '夜哈-劉俊朗.jpg',
    url: '【纯净哈基米】夜哈（夜曲） - 劉俊朗.mp3',
    bvid: 'BV1mbHpz7EQG',
    public_time: 1759377600,
  },
  {
    id: 6,
    title: '夜哈',
    artist: '慎啸',
    original: '夜曲-周杰伦',
    tags: ['vanilla'],
    playCount: 2825374,
    duration: 111,
    cover: '夜曲-慎啸.jpg',
    url: '【纯净哈基米】夜曲 - 慎啸.mp3',
    bvid: 'BV1pXnizLECc',
    public_time: 1759118368,
  },
  {
    id: 7,
    title: '我的哈基是咪做的',
    artist: '卿雪团子',
    original: '我的悲伤是水做的-洛天依',
    tags: ['cover', 'HaNiuMo'],
    playCount: 37237,
    duration: 95,
    cover: '我的哈基是咪做的-卿雪团子.jpg',
    url: '我的哈基是咪做的 - 卿雪团子.mp3',
    bvid: 'BV1kipfzGE3U',
    public_time: 1758427034,
  },
  {
    id: 8,
    title: '神曼波',
    artist: '月底没钱君',
    original: '神曼波',
    tags: ['ai'],
    playCount: 2518981,
    duration: 152,
    cover: '神曼波-月底没钱君.jpg',
    url: '神曼波 - 月底没钱君.mp3',
    bvid: 'BV1BfHKzXEC1',
    public_time: 1759449600,
  },
  {
    id: 9,
    title: '神曼波',
    artist: '慎啸',
    original: '神曼波-月底没钱君',
    tags: ['vanilla'],
    playCount: 108034,
    duration: 152,
    cover: '神曼波-慎啸.jpg',
    url: '神曼波 - 慎啸.mp3',
    bvid: 'BV1bD4wz3EmE',
    public_time: 1760194032,
  },
  {
    id: 10,
    title: '惬意の小曲-',
    artist: '慎啸',
    original: 'Bygone Gumps-Deep East Music',
    tags: ['DingDongJi'],
    playCount: 27750,
    duration: 127,
    cover: 'BygoneGumps-慎啸.jpg',
    url: 'Bygone Gumps - 慎啸.mp3',
    bvid: 'BV17tWizVE6v',
    public_time: 1760594066,
  },
  {
    id: 11,
    title: '基米冰城',
    artist: '听乐府',
    original: '蜜雪冰城',
    tags: ['vanilla'],
    playCount: 63705,
    duration: 116,
    cover: '基米冰城-听乐府.jpg',
    url: '基米冰城 - 听乐府.mp3',
    bvid: 'BV17tWizVE6v',
    public_time: 1753973513,
  },
  {
    id: 12,
    title: 'That Cat',
    artist: '天气温云',
    original: 'That Girl-Olly Murs',
    tags: ['lyric', 'DingDongJi', 'affectionate'],
    playCount: 1696401,
    duration: 134,
    cover: 'ThatCat-天气温云.jpg',
    url: 'That Cat - 天气温云.mp3',
    bvid: 'BV1YzxqzrENb', 
    lyric: 'ThatCat-天气温云.lrc',
    public_time: 1759973400,
  },
  {
    id: 13,
    title: '月光奏鸣曲第三乐章',
    artist: '红晓音Akane',
    original: '月光奏鸣曲第三乐章-贝多芬',
    tags: ['cover', 'classical'],
    playCount: 661257,
    duration: 101,
    cover: '月光奏鸣曲第三乐章-红晓音Akane.jpg',
    url: '【古典哈基米】月光奏鸣曲第三乐章 - 红晓音Akane.mp3',
    bvid: 'BV1kPJZzeEYQ',
    public_time: 1758600600,
  },
  {
    id: 14,
    title: '转生异世界の小曲',
    artist: '我叫小白李',
    original: 'Rasa Sayang-Saykoji',
    tags: ['vanilla'],
    playCount: 35978,
    duration: 67,
    cover: 'RasaSayang-我叫小白李.jpg',
    url: '【纯净哈基米】Rasa Sayang - 我叫小白李.mp3',
    bvid: 'BV1h1H5zeEyb',
    public_time: 1759505453,
  },
  {
    id: 15,
    title: '神曼波',
    artist: '宫泽遥-haruka',
    original: '神曼波-月底没钱君',
    tags: ['cover', 'vanilla'],
    playCount: 63878,
    duration: 151,
    cover: '神曼波-宫泽遥-haruka.jpg',
    url: '【职业民美翻唱】神曼波 - 宫泽遥-haruka.mp3',
    bvid: 'BV1Ye4uzNErr',
    public_time: 1760258687,
  },
  {
    id: 16,
    title: '基溺',
    artist: '我才不是小猫呢',
    original: '悬溺-葛东琪',
    tags: ['DingDongJi'],
    playCount: 520490,
    duration: 194,
    cover: '基溺-我才不是小猫呢.jpg',
    url: '【哈基米音乐】基溺 - 我才不是小猫呢.mp3',
    bvid: 'BV1MD4ezhEgb',
    public_time: 1760501955,
  },
  {
    id: 17,
    title: '蓝莲哈',
    artist: '猫猫怕痛惹',
    original: '蓝莲花-许巍',
    tags: ['vanilla'],
    playCount: 4781761,
    duration: 89,
    cover: '蓝莲哈-猫猫怕痛惹.jpg',
    url: '【纯净哈基米】蓝莲哈 - 猫猫怕痛惹.mp3',
    bvid: 'BV18M83zrECY',
    public_time: 1753612644,
  },
  {
    id: 18,
    title: '哈雪大冒险',
    artist: '暗杠读秒p',
    original: '滑雪大冒险-Soundroll',
    tags: ['GuiChu', 'DianGun', 'PangBaoBao', 'LiLiYuanShangMi', 'GuanTouYinXiao'],
    playCount: 13002939,
    duration: 196,
    cover: '哈雪大冒险-暗杠读秒p.jpg',
    url: '【哈基米音乐】哈雪大冒险 - 暗杠读秒p.mp3',
    bvid: 'BV1gQetekE5P',
    public_time: 1723727262,
  },
  {
    id: 19,
    title: '曼波大战基米：哈基博士',
    artist: '希灵empire',
    original: 'Ultimate Battle-Laura Shigihara',
    tags: ['DingDongJi', 'LiLiYuanShangMi', 'HaNiuMo'],
    playCount: 131301,
    duration: 104,
    cover: '哈基博士-希灵empire.jpg',
    url: '【哈基米音乐】曼波大战基米：哈基博士 - 希灵empire.mp3',
    bvid: 'BV16THVzrEWv',
    lyric: '',
    public_time: 1759489097,
  },
  {
    id: 20,
    title: '基米说',
    artist: '慎啸',
    original: '伯虎说-唐伯虎Annie/伯爵Johnny',
    tags: ['DingDongJi'],
    playCount: 3676449,
    duration: 156,
    cover: '基米说-慎啸.jpg',
    url: '【哈基米音乐】基米说（完整版） - 慎啸.mp3',
    bvid: 'BV1sdaHzTEe7',
    public_time: 1756733881,
  },
  {
    id: 21,
    title: 'No基米',
    artist: '云落夏天',
    original: 'Nobody-Wonder Girls',
    tags: ['DingDongJi', 'LiLiYuanShangMi', 'DianGun'],
    playCount: 110493,
    duration: 215,
    cover: 'No基米-云落夏天.jpg',
    url: '【哈基米音乐】No基米 - 云落夏天.mp3',
    bvid: 'BV1i7FWeUEpG',
    public_time: 1738159200,
  },
  {
    id: 22,
    title: '跳楼机曼波版',
    artist: '一根华仔',
    original: '跳楼机-LBI利比',
    tags: ['manbo'],
    playCount: 3912694,
    duration: 150,
    cover: '跳楼机曼波版-一根华仔.jpg',
    url: '跳楼机曼波版 - 一根华仔.mp3',
    bvid: 'BV1q9AYedE12',
    public_time: 1739926800,
  },
  {
    id: 23,
    title: '跳楼基',
    artist: '法兰西诗歌剧',
    original: '跳楼机-LBI利比',
    tags: ['vanilla'],
    playCount: 6423978,
    duration: 38,
    cover: '跳楼基-法兰西诗歌剧.jpg',
    url: '【哈基米音乐】跳楼基 - 法兰西诗歌剧.mp3',
    bvid: 'BV1N3PpezEpv',
    public_time: 1740630651,
  },
  {
    id: 24,
    title: '打火基',
    artist: '音乐老友',
    original: '打火机-Penny',
    tags: ['vanilla'],
    playCount: 1574604,
    duration: 62,
    cover: '打火基-音乐老友.jpg',
    url: '【纯净哈基米】打火基 - 音乐老友.mp3',
    bvid: 'BV16mn8zsE4x',
    public_time: 1758821871,
  },
  {
    id: 25,
    title: '哈基山的基米美如水啊',
    artist: '初小晓Dawn',
    original: '阿里山的姑娘-羊音乐',
    tags: ['vanilla'],
    playCount: 8056642,
    duration: 100,
    cover: '哈基山的基米美如水啊-初小晓Dawn.jpg',
    url: '【纯净哈基米】哈基山的基米美如水啊 - 初小晓Dawn.mp3',
    bvid: 'BV1vgYVzfEuF',
    public_time: 1757228738,
  },
  {
    id: 26,
    title: 'Free haji',
    artist: '初小晓Dawn',
    original: 'Free Loop-Daniel Powter',
    tags: ['vanilla'],
    playCount: 1333068,
    duration: 133,
    cover: 'FreeHaji-初小晓Dawn.jpg',
    url: '【纯净哈基米】Free haji - 初小晓Dawn.mp3',
    bvid: 'BV1pYJSzkEFi',
    public_time: 1758704400,
  },
  {
    id: 27,
    title: '柠檬树上哈基果',
    artist: '初小晓Dawn',
    original: 'Lemon Tree-Fool‘s Garden',
    tags: ['vanilla'],
    playCount: 1535466,
    duration: 139,
    cover: '柠檬树上哈基果-初小晓Dawn.jpg',
    url: '【纯净哈基米】柠檬树上哈基果 - 初小晓Dawn.mp3',
    bvid: 'BV1XhnRzGEcg',
    public_time: 1759050300,
  },
  {
    id: 28,
    title: '不再曼波',
    artist: '还给我神ID',
    original: 'Normal No More-TYSM',
    tags: ['vanilla'],
    playCount: 5802834,
    duration: 195,
    cover: '不再曼波-还给我神ID.jpg',
    url: '【纯净哈基米】不再曼波 - 还给我神ID.mp3',
    bvid: 'BV1qzFmeQEap',
    public_time: 1738301940,
  },
  {
    id: 29,
    title: '青基',
    artist: '慎啸',
    original: '青衣-草帽酱',
    tags: ['vanilla'],
    playCount: 1077801,
    duration: 188,
    cover: '青衣-慎啸.jpg',
    url: '【纯净哈基米】青衣 - 慎啸.mp3',
    bvid: 'BV1gFHyzmEh7',
    public_time: 1757421422,
  },
  {
    id: 30,
    title: '青哈',
    artist: '慎啸',
    original: '青丝-时光胶囊',
    tags: ['vanilla'],
    playCount: 351057,
    duration: 153,
    cover: '青丝-慎啸.jpg',
    url: '【纯净哈基米】青丝 - 慎啸.mp3',
    bvid: 'BV1xoJ1z6EtC',
    public_time: 1758628189,
  },
  {
    id: 31,
    title: '难得哈基米',
    artist: '慎啸',
    original: '难得真兄弟-何流/宋晓峰',
    tags: ['vanilla'],
    playCount: 792897,
    duration: 197,
    cover: '难得哈基米-慎啸.jpg',
    url: '【纯净哈基米】难得哈基米 - 慎啸.mp3',
    bvid: 'BV1MAY5zWEPS',
    public_time: 1757248200,
  },
  {
    id: 32,
    title: '难得哈基米',
    artist: '强者来了374',
    original: '难得真兄弟-何流/宋晓峰',
    tags: ['DingDongJi', 'PangBaoBao', 'HaNiuMo', 'DianGun'],
    playCount: 240193,
    duration: 56,
    cover: '难得哈基米-强者来了374.jpg',
    url: '【哈基米音乐】难得哈基米 - 强者来了374.mp3',
    bvid: 'BV1HDE9zXEt2',
    public_time: 1747657148,
  },
  {
    id: 33,
    title: '死别',
    artist: 'CannonGary',
    original: '死别-Shannon feat. GUMI',
    tags: ['DingDongJi'],
    playCount: 476172,
    duration: 62,
    cover: '死别-CannonGary.jpg',
    url: '【哈基米音乐】死别 - CannonGary.mp3',
    bvid: 'BV1yVEZzeEzV',
    public_time: 1747693078,
  },
  {
    id: 34,
    title: '圆头耄帝独断万古',
    artist: '电警喵',
    original: '荒天帝独断万古-王星',
    tags: ['vanilla'],
    playCount: 1646562,
    duration: 175,
    cover: '圆头耄帝独断万古-电警喵.jpg',
    url: '【纯净哈基米】圆头耄帝独断万古 - 电警喵.mp3',
    bvid: 'BV1gELPzDEp2',
    public_time: 1745229600,
  },
  {
    id: 35,
    title: '最后一哈',
    artist: '沐源鸽',
    original: '最后一页-洛尘鞅',
    tags: ['vanilla'],
    playCount: 3707164,
    duration: 208,
    cover: '最后一哈-沐源鸽.jpg',
    url: '【纯净哈基米】最后一哈 - 沐源鸽.mp3',
    bvid: 'BV1L6uszvE5u',
    public_time: 1752642987,
  },
  {
    id: 36,
    title: '起哈了',
    artist: 'Sh1awase',
    original: '起风了-买辣椒也用券',
    tags: ['vanilla'],
    playCount: 389504,
    duration: 331,
    cover: '起哈了-Sh1awase.jpg',
    url: '【纯净哈基米】起哈了 - Sh1awase.mp3',
    bvid: 'BV1TCn1zVErT',
    public_time: 1752642987,
  },
  {
    id: 37,
    title: '你的耄字',
    artist: '4zcre5naq_',
    original: 'スパークル-花火',
    tags: ['DingDongJi', 'PangBaoBao'],
    playCount: 2744199,
    duration: 131,
    cover: '你的耄字-4zcre5naq_.jpg',
    url: '【哈基米音乐】你的耄字 - 4zcre5naq_.mp3',
    bvid: 'BV1E2YPzVEUc',
    public_time: 1752642987,
  },
  {
    id: 38,
    title: '年轮',
    artist: '树深时见鹿dear',
    original: '年轮-汪苏泷',
    tags: ['DingDongJi'],
    playCount: 1647182,
    duration: 61,
    cover: '年轮-树深时见鹿dear.jpg',
    url: '【哈基米音乐】年轮 - 树深时见鹿dear.mp3',
    bvid: 'BV11588zJEhf',
    public_time: 1753533927,
  },
  {
    id: 39,
    title: '哈基会序曲',
    artist: '暗杠读秒p',
    original: '小刀会序曲-林友声/上海乐团管弦乐队',
    tags: ['DingDongJi', 'DianGun', 'PangBaoBao', 'DianGun', 'LiLiYuanShangMi'],
    playCount: 661798,
    duration: 45,
    cover: '哈基会序曲-暗杠读秒p.jpg',
    url: '【哈基米音乐】哈基会序曲 - 暗杠读秒p.mp3',
    bvid: 'BV1cJpbeAEeN',
    public_time: 1725722401,
  },
  {
    id: 40,
    title: '哈基米的澎湖湾',
    artist: '鼻血黄豆来了',
    original: '外婆的澎湖湾-潘安邦',
    tags: ['DingDongJi', 'DianGun', 'PangBaoBao', 'DianGun', 'LiLiYuanShangMi'],
    playCount: 585131,
    duration: 89,
    cover: '哈基米的澎湖湾-鼻血黄豆来了.jpg',
    url: '【哈基米音乐】哈基米的澎湖湾 - 鼻血黄豆来了.mp3',
    bvid: 'BV17b421p7aC',
    public_time: 1719556176,
  },
  {
    id: 41,
    title: '舌尖上的哈基米',
    artist: '面点海',
    original: '片头音乐-啊鲲',
    tags: ['DingDongJi'],
    playCount: 2765911,
    duration: 51,
    cover: '舌尖上的哈基米-面点海.jpg',
    url: '【哈基米音乐】舌尖上的哈基米 - 面点海.mp3',
    bvid: 'BV1F8EDz6EFg',
    public_time: 1747625233,
  },
  {
    id: 42,
    title: '曼波你身',
    artist: '挥一挥衣秀',
    original: 'Move Your Body-RAIZHELL',
    tags: ['vanilla'],
    playCount: 2680080,
    duration: 152,
    cover: '曼波你身-挥一挥衣秀.jpg',
    url: '【纯净哈基米】曼波你身 - 挥一挥衣秀.mp3',
    bvid: 'BV1E7CwYHEDN',
    public_time: 1735113335,
  },
  {
    id: 43,
    title: '两个笨蛋',
    artist: '京桥刹那',
    original: '马鹿ふたり-折戸伸治',
    tags: ['vanilla'],
    playCount: 3003176,
    duration: 32,
    cover: '两个笨蛋-京桥刹那.jpg',
    url: '【纯净哈基米】两个笨蛋 - 京桥刹那.mp3',
    bvid: 'BV1N14y1p7G3',
    public_time: 1668852000,
  },
  {
    id: 44,
    title: '祝我生日快乐',
    artist: '零号元素N',
    original: '生日快乐歌',
    tags: ['vanilla'],
    playCount: 3057,
    duration: 117,
    cover: '祝我生日快乐-零号元素N.jpg',
    url: '【纯净哈基米】祝我生日快乐 - 零号元素N.mp3',
    bvid: 'BV1XkWBzrE99',
    public_time: 1760659200,
  },
  {
    id: 45,
    title: '基不落',
    artist: '劉俊朗',
    original: '日不落-蔡依林',
    tags: ['cover'],
    playCount: 199493,
    duration: 76,
    cover: '基不落-劉俊朗.jpg',
    url: '【哈基米音乐】基不落 - 劉俊朗.mp3',
    bvid: 'BV1E7WrzxE8L',
    public_time: 1760673600,
  },
  {
    id: 46,
    title: '你哈到的我',
    artist: '百合园小咲',
    original: '你看到的我-黄勇/任书怀',
    tags: ['vanilla'],
    playCount: 53800,
    duration: 114,
    cover: '你哈到的我-百合园小咲.jpg',
    url: '【纯净哈基米】你哈到的我 - 百合园小咲.mp3',
    bvid: 'BV1FAWvzrEVH',
    public_time: 1760605154,
  },
  {
    id: 47,
    title: '打上花火',
    artist: '沐沐叁水宣',
    original: '打上花火-Daoko/米津玄師',
    tags: ['vanilla'],
    playCount: 175559,
    duration: 284,
    cover: '打上花火-沐沐叁水宣.jpg',
    url: '【纯净哈基米】打上花火 （完整版） - 沐沐叁水宣.mp3',
    bvid: 'BV1rSpcz7E8t',
    public_time: 1757841950,
  },
  {
    id: 48,
    title: '压迫感の小曲',
    artist: '慎啸',
    original: 'O Come O Come Emmanuel-Tommee Profitt',
    tags: ['DingDongJi', 'HaNiuMo', 'DianGun', 'PangBaoBao', 'LiLiYuanShangMi', 'GuGuGaGa'],
    playCount: 38299,
    duration: 193,
    cover: '压迫感の小曲-慎啸.jpg',
    url: '【哈基米音乐】压迫感の小曲（O Come O Come Emmanuel） - 慎啸.mp3',
    bvid: 'BV1zdWEzcETv',
    public_time: 1760691129,
  },
  {
    id: 49,
    title: '反方向的哈',
    artist: '凉老ye不鸽',
    original: '反方向的钟-周杰伦',
    tags: ['DingDongJi', 'PangBaoBao', 'LiLiYuanShangMi'],
    playCount: 42961,
    duration: 168,
    cover: '反方向的哈-凉老ye不鸽.jpg',
    url: '【哈基米音乐】反方向的哈 - 凉老ye不鸽.mp3',
    bvid: 'BV1dW4tz9EGv',
    public_time: 1760439505,
  },
  {
    id: 50,
    title: '青哈瓷',
    artist: 'Ab_Wesker',
    original: '青花瓷-周杰伦',
    tags: ['DingDongJi', 'DianGun'],
    playCount: 282202,
    duration: 93,
    cover: '青哈瓷-Ab_Wesker.jpg',
    url: '【哈基米音乐】青哈瓷 - Ab_Wesker.mp3',
    bvid: 'BV1UCZPYGEAZ',
    public_time: 1743007985,
  },
  {
    id: 51,
    title: '把基米拼好给你',
    artist: 'Sh1awase',
    original: '把回忆拼好给你-王贰浪',
    tags: ['HaNiuMo'],
    playCount: 317367,
    duration: 114,
    cover: '把基米拼好给你-Sh1awase.jpg',
    url: '【哈基米音乐】把基米拼好给你 - Sh1awase.mp3',
    bvid: 'BV14LWPzwE8s',
    public_time: 1758449100,
  },
  {
    id: 52,
    title: '哈人错过',
    artist: '爱言叶呐',
    original: '爱人错过-告五人',
    tags: ['DingDongJi', 'GuGuGaGa', 'PangBaoBao', 'DianGun'],
    playCount: 429207,
    duration: 216,
    cover: '哈人错过-爱言叶呐.jpg',
    url: '【哈基米音乐】哈人错过 - 爱言叶呐.mp3',
    bvid: 'BV12ybQzLEBW',
    public_time: 1753436654,
  },
  {
    id: 53,
    title: '悬疑哈基米',
    artist: '绿巨羊o',
    original: 'Conundrum-',
    tags: ['DingDongJi', 'LiLiYuanShangMi', 'PangBaoBao'],
    playCount: 1323985,
    duration: 149,
    cover: 'Conundrum-绿巨羊o.jpg',
    url: '【哈基米音乐】悬疑哈基米（Conundrum） - 绿巨羊o.mp3',
    bvid: 'BV1MdKMzzEFH',
    public_time: 1750742271,
  },
  {
    id: 54,
    title: '哈基米起床',
    artist: '面点海',
    original: 'おはなば たけ-花田',
    tags: ['DingDongJi'],
    playCount: 906446,
    duration: 33,
    cover: '哈基米起床-面点海.jpg',
    url: '【哈基米音乐】哈基米起床 - 面点海.mp3',
    bvid: 'BV1QzMjzuEdV',
    public_time: 1749605602,
  },
  {
    id: 55,
    title: '【古典哈基米】D大调小步舞曲-莫哈特（原曲不使用）',
    artist: '零号元素N',
    original: 'D大调小步舞曲-莫扎特',
    tags: ['classical'],
    playCount: 112638,
    duration: 278,
    cover: 'D大调小步舞曲-莫哈特-零号元素N.jpg',
    url: '【古典哈基米】D大调小步舞曲-莫哈特（原曲不使用） - 零号元素N.mp3',
    bvid: 'BV12FHKzAEws',
    public_time: 1759453200,
  },
  {
    id: 56,
    title: 'D大调哈农 Hanon in D（原曲不使用）',
    artist: '零号元素N',
    original: 'Canon in D Major-Johann Pachelbel',
    tags: ['classical'],
    playCount: 512615,
    duration: 311,
    cover: 'D大调哈农-零号元素N.jpg',
    url: '【古典哈基米】D大调哈农 Hanon in D（原曲不使用） - 零号元素N.mp3',
    bvid: 'BV1mRavz5EAu',
    public_time: 1757128390,
  },
  {
    id: 57,
    title: '哈山酒',
    artist: '_Yurine_',
    original: '关山酒-邓寓君(等什么君)',
    tags: ['DingDongJi', 'PangBaoBao', 'LiLiYuanShangMi'],
    playCount: 805462,
    duration: 102,
    cover: '哈山酒-_Yurine_.jpg',
    url: '【哈基米音乐】哈山酒 - _Yurine_.mp3',
    bvid: 'BV15UjbzcEMk',
    public_time: 1748080754,
  },
  {
    id: 58,
    title: '请不要哈气',
    artist: '416不想白给',
    original: 'Xin Đừng Nhấc Máy',
    tags: ['DingDongJi', 'ShiDaiShaoNianTuan', 'LiLiYuanShangMi'],
    playCount: 202564,
    duration: 205,
    cover: '请不要哈气-416不想白给.jpg',
    url: '【哈基米音乐】请不要哈气 - 416不想白给.mp3',
    bvid: 'BV1NPGAzhEvw',
    public_time: 1752072193,
  },
  {
    id: 59,
    title: '春节序曲',
    artist: '屾氙',
    original: '春节序曲-中国人民解放军军乐团',
    tags: ['DianGun', 'DingDongJi'],
    playCount: 345051,
    duration: 298,
    cover: '春节序曲-屾氙.jpg',
    url: '【哈基米音乐】春节序曲 - 屾氙.mp3',
    bvid: 'BV1C4FKeUED3',
    public_time: 1738159939,
  },
  {
    id: 60,
    title: '火红的哈基郎',
    artist: '南瓜水水',
    original: '火红的萨日朗-乌兰托娅',
    tags: ['DingDongJi'],
    playCount: 40315,
    duration: 31,
    cover: '火红的哈基郎-南瓜水水.jpg',
    url: '【哈基米音乐】火红的哈基郎 - 南瓜水水.mp3',
    bvid: 'BV1F7xHzrEjg',
    public_time: 1759548600,
  },
  {
    id: 61,
    title: '啊米诺斯',
    artist: 'kafy4325',
    original: 'Aminals-Maroon 5',
    tags: ['HaNiuMo', 'LiLiYuanShangMi', 'PangBaoBao', 'DianGun'],
    playCount: 36981,
    duration: 229,
    cover: '啊米诺斯-kafy4325.jpg',
    url: '【哈基米音乐】啊米诺斯（Aminals） - kafy4325.mp3',
    bvid: 'BV16xHAzUEQU',
    public_time: 1759398016,
  },
  {
    id: 62,
    title: '弱水三哈',
    artist: '-胡莱克修斯-',
    original: '弱水三千-石头/张晓棠',
    tags: ['HaNiuMo'],
    playCount: 448470,
    duration: 79,
    cover: '弱水三哈-胡莱克修斯.jpg',
    url: '【哈基米音乐】弱水三哈 - 胡莱克修斯.mp3',
    bvid: 'BV1zBWgz6EnR',
    public_time: 1758250950,
  },
  {
    id: 63,
    title: '夜哈',
    artist: '星落残响_-',
    original: '夜曲-周杰伦',
    tags: ['cover', 'vanilla'],
    playCount: 28918,
    duration: 91,
    cover: '夜哈-星落残响.jpg',
    url: '【哈基米音乐】夜哈 - 星落残响.mp3',
    bvid: 'BV13DW7z1ETv',
    public_time: 1760704855,
  },
  {
    id: 64,
    title: 'Hanama',
    artist: '初小晓Dawn',
    original: 'Panama-Matteo',
    tags: ['vanilla'],
    playCount: 149010,
    duration: 123,
    cover: 'Hanama-初小晓Dawn.jpg',
    url: '【哈基米音乐】Hanama - 初小晓Dawn.mp3',
    bvid: 'BV1ThxLzBEeJ',
    public_time: 1759741200,
  },
  {
    id: 65,
    title: 'PLANET',
    artist: '沐沐叁水宣',
    original: 'PLANET-ラムジ',
    tags: ['vanilla'],
    playCount: 45088,
    duration: 84,
    cover: 'PLANET-沐沐叁水宣.jpg',
    url: '【纯净哈基米】PLANET - 沐沐叁水宣.mp3',
    bvid: 'BV1HsHxzmE7i',
    public_time: 1759334276,
  },
  {
    id: 66,
    title: '以耋之名',
    artist: '红豆稀饭中',
    original: '以父之名-周杰伦',
    tags: ['DingDongJi'],
    playCount: 738733,
    duration: 225,
    cover: '以耋之名-红豆稀饭中.jpg',
    url: '【哈基米音乐】以耋之名 - 红豆稀饭中.mp3',
    bvid: 'BV16uHPzEEkx',
    public_time: 1759464000,
  },
  {
    id: 67,
    title: '哈不落',
    artist: 'cooikun',
    original: '日不落-',
    tags: ['vanilla'],
    playCount: 24520,
    duration: 69,
    cover: '哈不落-cooikun.jpg',
    url: '【纯净哈基米】哈不落 - cooikun.mp3',
    bvid: 'BV1kyxQzeEgF',
    public_time: 1759836410,
  },
  {
    id: 68,
    title: '哈ded-Alan 哈ker',
    artist: '咆哮丶土拨鼠',
    original: 'Faded-Alan Walker',
    tags: ['vanilla'],
    playCount: 94791,
    duration: 71,
    cover: '哈ded-咆哮丶土拨鼠.jpg',
    url: '【哈基米音乐】哈ded-Alan 哈ker - 咆哮丶土拨鼠.mp3',
    bvid: 'BV1p5n1zAEAA',
    public_time: 1759287600,
  },
  {
    id: 69,
    title: '听基米的哈',
    artist: '柴门雪夜',
    original: '听妈妈的话-周杰伦',
    tags: ['vanilla'],
    playCount: 5099,
    duration: 265,
    cover: '听基米的哈-柴门雪夜.jpg',
    url: '【哈基米音乐】听基米的哈 - 柴门雪夜.mp3',
    bvid: 'BV1gtWtz3EZr',
    public_time: 1760801199,
  },
  {
    id: 70,
    title: '欢快の小曲',
    artist: '慎啸',
    original: 'Barroom Ballet-Kevin MacLeod',
    tags: ['vanilla'],
    playCount: 140239,
    duration: 56,
    cover: '欢快の小曲-慎啸.jpg',
    url: '【纯净哈基米】欢快の小曲（Barroom Ballet） - 慎啸.mp3',
    bvid: 'BV1vtxvz3EdY',
    public_time: 1759929913,
  },
  {
    id: 71,
    title: '哈梅戏',
    artist: 'Ab_Wesker',
    original: '女驸马-王兆乾',
    tags: ['PekingOpera', 'DingDongJi', 'PangBaoBao'],
    playCount: 1013485,
    duration: 72,
    cover: '哈梅戏-Ab_Wesker.jpg',
    url: '【哈基米京剧】哈梅戏 - Ab_Wesker.mp3',
    bvid: 'BV1h8RiYhEpv',
    public_time: 1743919043,
  },
  {
    id: 72,
    title: '卖水',
    artist: '汉文不姓许',
    original: '卖水-由刘长瑜/萧润德',
    tags: ['PekingOpera', 'cover', 'vanilla'],
    playCount: 203996,
    duration: 40,
    cover: '卖水-汉文不姓许.jpg',
    url: '【哈基米京剧】卖水 - 汉文不姓许.mp3',
    bvid: 'BV1NGWszRE44',
    public_time: 1760768171,
  },
  {
    id: 73,
    title: '哈如雪',
    artist: '凉老ye不鸽',
    original: '发如雪-周杰伦',
    tags: ['vanilla'],
    playCount: 455993,
    duration: 189,
    cover: '哈如雪-凉老ye不鸽.jpg',
    url: '【纯净哈基米】哈如雪 - 凉老ye不鸽.mp3',
    bvid: 'BV1ztxjzbEoL',
    public_time: 1759749685,
  },
  {
    id: 74,
    title: '小幸运',
    artist: '天霜亦无痕',
    original: '小幸运-田馥甄',
    tags: ['vanilla'],
    playCount: 2982,
    duration: 64,
    cover: '小幸运-天霜亦无痕.jpg',
    url: '【纯净哈基米】小幸运 - 天霜亦无痕.mp3',
    bvid: 'BV18j4bzEEb9',
    public_time: 1760431797,
  },
  {
    id: 75,
    title: "米基玄师 - I'm 基米",
    artist: '希灵empire',
    original: 'LOSER-米津玄師',
    tags: ['lyric', 'DingDongJi'],
    playCount: 8802,
    duration: 61,
    cover: 'LOSER-希灵empire.jpg',
    url: '【哈基米音乐】米基玄师 - LOSER - 希灵empire.mp3',
    bvid: 'BV1UqWtzNEFj',
    public_time: 1760847300,
  },
  {
    id: 76,
    title: '庐州哈',
    artist: 'cooikun',
    original: '庐州月-许嵩',
    tags: ['DingDongJi', 'HaNiuMo'],
    playCount: 33543,
    duration: 108,
    cover: '庐州哈-cooikun.jpg',
    url: '【哈基米音乐】庐州哈 - cooikun.mp3',
    bvid: 'BV1DsWqzPEEB',
    public_time: 1760614632,
  },
  {
    id: 77,
    title: '偏哈',
    artist: 'cooikun',
    original: '偏爱-张芸京',
    tags: ['DingDongJi'],
    playCount: 72266,
    duration: 96,
    cover: '偏哈-cooikun.jpg',
    url: '【哈基米音乐】偏哈 - cooikun.mp3',
    bvid: 'BV1aNnJzVEPD',
    public_time: 1758957897,
  },
  {
    id: 78,
    title: '一万个哈不得',
    artist: 'ZhenXea',
    original: '一万个舍不得-庄心妍',
    tags: ['vanilla'],
    playCount: 92234,
    duration: 208,
    cover: '一万个哈不得-ZhenXea.jpg',
    url: '【纯净哈基米】一万个哈不得 - ZhenXea.mp3',
    bvid: 'BV1LBnJzDExE',
    public_time: 1758967200,
  },
  {
    id: 79,
    title: '哈墙',
    artist: '_小火子_',
    original: '心墙-',
    tags: ['vanilla'],
    playCount: 8234,
    duration: 95,
    cover: '哈墙-_小火子_.jpg',
    url: '【纯净哈基米】哈墙 - _小火子_.mp3',
    bvid: 'BV1omnqzqEat',
    public_time: 1759280400,
  },
];