window['musicData'] = [
  {
    id: 1,
    title: 'Golden Hour',
    artist: '慎啸',
    original: 'Golden Hour-JVKE',
    tags: ['vanilla'],
    playCount: 747053,
    duration: 211,
    cover: 'GoldenHour-慎啸.jpg',
    url: '【纯净哈基米】Golden Hour - 慎啸.mp3',
    bvid: 'BV1aQnGzZE8e',
    lyric: 'GoldenHour-慎啸.lrc',
    public_time: 1758890132,
  },
  {
    id: 2,
    title: '基米地',
    artist: 'kizznoluv',
    original: '凄美地-郭顶',
    tags: ['vanilla'],
    playCount: 90926,
    duration: 91,
    cover: '基米地-kizznoluv.jpg',
    url: '【纯净哈基米】基米地（凄美地） - kizznoluv.mp3',
    bvid: 'BV1d5phzXEFs',
    public_time: 1758160800,
  },
  {
    id: 3,
    title: '匆匆哈年',
    artist: '慎啸',
    original: '匆匆那年-王菲',
    tags: ['vanilla'],
    playCount: 169643,
    duration: 242,
    cover: '匆匆哈年-慎啸.jpg',
    url: '【纯净哈基米】匆匆哈年（完整版） - 慎啸.mp3',
    bvid: 'BV1pc42zpEX7',
    public_time: 1760362656,
  },
  {
    id: 4,
    title: '基米说',
    artist: '劉俊朗',
    original: '伯虎说-唐伯虎Annie/伯爵Johnny',
    tags: ['cover', 'DingDongJi'],
    playCount: 7948136,
    duration: 242,
    cover: '基米说-劉俊朗.jpg',
    url: '基米说（完整版） - 劉俊朗.mp3',
    bvid: 'BV1Dua2zyE4G',
    public_time: 1756960147,
  },
  {
    id: 5,
    title: '夜哈',
    artist: '劉俊朗',
    original: '夜曲-周杰伦',
    tags: ['cover', 'vanilla'],
    playCount: 1685507,
    duration: 113,
    cover: '夜哈-劉俊朗.jpg',
    url: '【纯净哈基米】夜哈（夜曲） - 劉俊朗.mp3',
    bvid: 'BV1mbHpz7EQG',
    public_time: 1759377600,
  },
  {
    id: 6,
    title: '夜哈',
    artist: '慎啸',
    original: '夜曲-周杰伦',
    tags: ['vanilla'],
    playCount: 2825374,
    duration: 111,
    cover: '夜曲-慎啸.jpg',
    url: '【纯净哈基米】夜曲 - 慎啸.mp3',
    bvid: 'BV1pXnizLECc',
    public_time: 1759118368,
  },
  {
    id: 7,
    title: '我的哈基是咪做的',
    artist: '卿雪团子',
    original: '我的悲伤是水做的-洛天依',
    tags: ['cover', 'HaNiuMo'],
    playCount: 37237,
    duration: 95,
    cover: '我的哈基是咪做的-卿雪团子.jpg',
    url: '我的哈基是咪做的 - 卿雪团子.mp3',
    bvid: 'BV1kipfzGE3U',
    public_time: 1758427034,
  },
  {
    id: 8,
    title: '神曼波',
    artist: '月底没钱君',
    original: '神曼波',
    tags: ['ai'],
    playCount: 2518981,
    duration: 152,
    cover: '神曼波-月底没钱君.jpg',
    url: '神曼波 - 月底没钱君.mp3',
    bvid: 'BV1BfHKzXEC1',
    public_time: 1759449600,
  },
  {
    id: 9,
    title: '神曼波',
    artist: '慎啸',
    original: '神曼波-月底没钱君',
    tags: ['vanilla'],
    playCount: 108034,
    duration: 152,
    cover: '神曼波-慎啸.jpg',
    url: '神曼波 - 慎啸.mp3',
    bvid: 'BV1bD4wz3EmE',
    public_time: 1760194032,
  },
  {
    id: 10,
    title: '惬意の小曲-',
    artist: '慎啸',
    original: 'Bygone Gumps-Deep East Music',
    tags: ['DingDongJi'],
    playCount: 27750,
    duration: 127,
    cover: 'BygoneGumps-慎啸.jpg',
    url: 'Bygone Gumps - 慎啸.mp3',
    bvid: 'BV17tWizVE6v',
    public_time: 1760594066,
  },
  {
    id: 11,
    title: '基米冰城',
    artist: '听乐府',
    original: '蜜雪冰城',
    tags: ['vanilla'],
    playCount: 63705,
    duration: 116,
    cover: '基米冰城-听乐府.jpg',
    url: '基米冰城 - 听乐府.mp3',
    bvid: 'BV17tWizVE6v',
    public_time: 1753973513,
  },
  {
    id: 12,
    title: 'That Cat',
    artist: '天气温云',
    original: 'That Girl-Olly Murs',
    tags: ['DingDongJi', 'affectionate'],
    playCount: 1696401,
    duration: 134,
    cover: 'ThatCat-天气温云.jpg',
    url: 'That Cat - 天气温云.mp3',
    bvid: 'BV1YzxqzrENb', 
    lyric: 'ThatCat-天气温云.lrc',
    public_time: 1759973400,
  },
  {
    id: 13,
    title: '月光奏鸣曲第三乐章',
    artist: '红晓音Akane',
    original: '月光奏鸣曲第三乐章-贝多芬',
    tags: ['cover', 'classical'],
    playCount: 661257,
    duration: 101,
    cover: '月光奏鸣曲第三乐章-红晓音Akane.jpg',
    url: '【古典哈基米】月光奏鸣曲第三乐章 - 红晓音Akane.mp3',
    bvid: 'BV1kPJZzeEYQ',
    public_time: 1758600600,
  },
  {
    id: 14,
    title: '转生异世界の小曲',
    artist: '我叫小白李',
    original: 'Rasa Sayang-Saykoji',
    tags: ['vanilla'],
    playCount: 35978,
    duration: 67,
    cover: 'RasaSayang-我叫小白李.jpg',
    url: '【纯净哈基米】Rasa Sayang - 我叫小白李.mp3',
    bvid: 'BV1h1H5zeEyb',
    public_time: 1759505453,
  },
  {
    id: 15,
    title: '神曼波',
    artist: '宫泽遥-haruka',
    original: '神曼波-月底没钱君',
    tags: ['cover', 'vanilla'],
    playCount: 63878,
    duration: 151,
    cover: '神曼波-宫泽遥-haruka.jpg',
    url: '【职业民美翻唱】神曼波 - 宫泽遥-haruka.mp3',
    bvid: 'BV1Ye4uzNErr',
    public_time: 1760258687,
  },
  {
    id: 16,
    title: '基溺',
    artist: '我才不是小猫呢',
    original: '悬溺-葛东琪',
    tags: ['DingDongJi'],
    playCount: 520490,
    duration: 194,
    cover: '基溺-我才不是小猫呢.jpg',
    url: '【哈基米音乐】基溺 - 我才不是小猫呢.mp3',
    bvid: 'BV1MD4ezhEgb',
    public_time: 1760501955,
  },
  {
    id: 17,
    title: '蓝莲哈',
    artist: '猫猫怕痛惹',
    original: '蓝莲花-许巍',
    tags: ['vanilla'],
    playCount: 4781761,
    duration: 89,
    cover: '蓝莲哈-猫猫怕痛惹.jpg',
    url: '【纯净哈基米】蓝莲哈 - 猫猫怕痛惹.mp3',
    bvid: 'BV18M83zrECY',
    public_time: 1753612644,
  },
  {
    id: 18,
    title: '哈雪大冒险',
    artist: '暗杠读秒p',
    original: '滑雪大冒险-Soundroll',
    tags: ['GuiChu', 'DianGun', 'PangBaoBao', 'LiLiYuanShangMi', 'GuanTouYinXiao'],
    playCount: 13002939,
    duration: 196,
    cover: '哈雪大冒险-暗杠读秒p.jpg',
    url: '【哈基米音乐】哈雪大冒险 - 暗杠读秒p.mp3',
    bvid: 'BV1gQetekE5P',
    public_time: 1723727262,
  },
  {
    id: 19,
    title: '曼波大战基米：哈基博士',
    artist: '希灵empire',
    original: 'Ultimate Battle-Laura Shigihara',
    tags: ['DingDongJi', 'LiLiYuanShangMi', 'HaNiuMo'],
    playCount: 131301,
    duration: 104,
    cover: '哈基博士-希灵empire.jpg',
    url: '【哈基米音乐】曼波大战基米：哈基博士 - 希灵empire.mp3',
    bvid: 'BV16THVzrEWv',
    lyric: '',
    public_time: 1759489097,
  },
];